[book]
authors = ["Daid"]
language = "en"
multilingual = false
src = "src"
title = "Gameboy Software Development Kit"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/daid/gbsdk/tree/book"

[output.linkcheck]
follow-web-links = true
optional = true
