name: github pages

on:
  push:
    branches:
      - book
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.8'
          # mdbook-version: 'latest'

      - name: Install mdbook-linkcheck
        run: |
          curl -L -o mdbook-linkcheck.zip "https://github.com/Michael-F-Bryan/mdbook-linkcheck/releases/download/v0.7.4/mdbook-linkcheck.v0.7.4.x86_64-unknown-linux-gnu.zip"
          unzip mdbook-linkcheck.zip mdbook-linkcheck
          chmod +x mdbook-linkcheck
      - name: build
        env:
          MDBOOK_OUTPUT__LINKCHECK__COMMAND: "./mdbook-linkcheck"
        run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/book'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
